# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e646351dd658bd76b2506744c4ca9aca331d76d0e67d49bfb8223fe59bd58753796e5bb9cf0f19ebee277dfb22cfe56a133af36930f6b60eed0367b490cdeb49

test:
  secret_key_base: 381f1e7435f1696e38c303930e5a6f1dd0b905242e1386c3f268bcd09926aab9fdb3f56a886f96fb614e72077bfd8a90cedacf859d520606dfdaf7da3156e88f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
